New Changes
sharkoo0/WebTEX pull request #13
Opened 2021-03-30 21:50 UTC by adikrasimirowa

Making all files with the same style

2021-03-31 05:47 UTC, yavorp requested changes
Повече ми коментари относно стилизацията са ми вкарани в ишу. Ако съм коментирал по Pull Request, който не е за ревю, може да го отбелязвате като драфт. Draft Pull Requests няма да ги гледам

2021-03-31 05:47 UTC, yavorp commented on css/changeDetails.css
> -.content {
Използвайте отделен файл за стилизация вместо цялата стилизация да бъде в един файл

2021-03-31 05:47 UTC, yavorp commented on css/main.css
> +/* Style for myFiles,sharedFiles.html */
Използвайте main.css само за общи стилове. Тази стратегия не работи добре за повече от 2-3 файла.

2021-03-31 05:47 UTC, yavorp commented on css/main.css
> +#file-table th {
Не е добра праткика да използвате id-та като селектори. Това ще се оправи, когато си разделите къстъм стиловете, като този, във файл със стилове за конкретния екран

2021-03-31 05:47 UTC, yavorp commented on html/myFiles.html
> +            <!-- <li><h1 class="logo">MyCloud</h1></li> -->
Не оставяйте закоментиран код

2021-03-31 05:47 UTC, yavorp commented on html/myFiles.html
>  <!-- NAVBAR -->
Използвайте семантичния таг `nav` за място, на което има неща, които отговарят за навигацията.

2021-03-31 05:47 UTC, yavorp commented on html/myFiles.html
>              <tr>
Използвайте `thead`, за да си отделите хедърите от тялото на таблицата, по този начин ще можете по-лесно да си стилизирате таблиците

2021-03-31 05:47 UTC, yavorp commented on html/userDetails.html
>              <table>
Използвайте `flex` и `grid`. Имате отворено ишу с повече информация

2021-03-31 05:47 UTC, yavorp commented on html/userDetails.html
> +    <!-- USER DETAILS -->
Очевидни коментари може да не влизат в Pull Request-ите. За някакъв дебъг е окей да ги има, но след това е добре да бъдат изтрити, за да поддържате по-чисто репо. А в повечето случаи такива коментари могат да бъдат избегнати с правилното именуване на класове или променливи

2021-03-31 09:55 UTC, yavorp commented on html/userDetails.html
>                          <br><br><br>
Може да използвате `flex` със `flex-gap`,вместо тези 3 реда. Те не са добра практика

2021-03-31 09:57 UTC, yavorp commented on css/main.css
> +.details-content {
Бъдете по-консистентни, `<property>: <value>`, a не `<property>:<value>`

2021-03-31 12:53 UTC, adikrasimirowa commented on html/userDetails.html
> +    <!-- USER DETAILS -->
Този вид коментари съм ги добавила за ориентир, тъй като някои членове в екипа  за първи път се занимават с HTML и все още свикват със синтаксиса и структурата. След това ще бъдат премахнати.

2021-03-31 13:45 UTC, adikrasimirowa commented on css/main.css
> +#file-table th {
Всички id-та са сменени с class селектори тук: 7a917e6465a122c3b8e712c2761b3acf12f13255 . Прегледах css-a и няма проблеми да са само class селектори, за сега няма повтарящи се класове

2021-03-31 13:51 UTC, adikrasimirowa commented on html/myFiles.html
> +            <!-- <li><h1 class="logo">MyCloud</h1></li> -->
Закоментираният код е премахнат:  ef7cf72a7a6f1200751122174d831476639961f6

2021-04-01 10:54 UTC, adikrasimirowa commented on html/userDetails.html
>              <table>
разбрахме се с @sharkoo0  да оправи нещата в userDetails.html в друг бранч, аз ще оправя останалите неща тук

2021-04-01 11:02 UTC, adikrasimirowa commented on css/changeDetails.css
> -.content {
разбрахме се с екипа, след като оправим останалите неща и мърджнем наново ще ги разделим

2021-04-02 10:35 UTC, adikrasimirowa commented on html/userDetails.html
>                          <br><br><br>
това също ще е към другия бранч който ще се прави от  @sharkoo0

2021-04-02 10:41 UTC, adikrasimirowa commented on css/main.css
> +/* Style for myFiles,sharedFiles.html */
Обсъдено в issue #14

2021-04-02 10:57 UTC, adikrasimirowa commented on html/myFiles.html
>  <!-- NAVBAR -->
Оправено в 735a5e879fcc2402219bcafef638dcc5050d1680

2021-04-02 10:58 UTC, adikrasimirowa commented on html/myFiles.html
>              <tr>
Добаен `thead` тук 28e83a48ef1de2df9756f2fca0636130060bb0da

2021-04-02 10:59 UTC, adikrasimirowa commented on css/main.css
> +.details-content {
CSS  e форматиран тук cd875a635149892d47af531c19d920ba0da6426e

2021-04-02 13:35 UTC, yavorp approved these changes
Моля да вземете под внимание забележките, които имам в бъдещите ви PR-и

2021-04-02 13:35 UTC, yavorp commented on html/userDetails.html
> +                        <td width="260" height="260" style="border-style:solid">
Inline стиловете не са добра практика

2021-04-02 13:35 UTC, yavorp commented on html/userDetails.html
> +                            <br><br><br>
`<br>`  Не се използва за добавяне на отстояния

2021-04-02 14:03 UTC, merged