Fix/separate main css adi
sharkoo0/WebTEX pull request #23
Opened 2021-04-06 21:24 UTC by adikrasimirowa

Както се разбрахме в #14 направих разпределение на стилизацията по файлове

2021-04-07 06:09 UTC, yavorp commented on css/main.css
> +    width: 24px;/*     float: right; */
Забравен коментар

2021-04-07 06:21 UTC, yavorp requested changes
Изберете си начин, по който да използвате основния css. Може да го импортвате в css-a на страницата или да го линкнете в страницата преди css-a на текущата страница.  Така както е направено в момента може да презапишете някои от специфичните стилизации с тези от основния css

2021-04-07 06:21 UTC, yavorp commented on html/login.html
>          <link rel="stylesheet" type="text/css" href="../css/main.css"/>
Има излишен импорт на основните стилове

2021-04-07 06:45 UTC, yavorp submitted a review, later dismissed

2021-04-07 06:57 UTC, sharkoo0 commented on css/main.css
> +    width: 20px;/*     float: left; */
Тук има още един коментар.

2021-04-07 10:56 UTC, sharkoo0 approved these changes

2021-04-08 06:37 UTC, adikrasimirowa commented on html/login.html
>          <link rel="stylesheet" type="text/css" href="../css/main.css"/>
Благодаря, попруснала съм го :D

2021-04-08 11:25 UTC, adikrasimirowa commented
По препоръка на  @sharkoo0 върнах css-а  на upload бутона в main css тъй като го имаме почти във всяка една страница

2021-04-08 12:17 UTC, kaloyan-dutsolov6 approved these changes

2021-04-08 17:52 UTC, yavorp commented on html/userDetails.html
> +        <!-- <form class="wrapper upload">
Коментиран код

2021-04-08 21:50 UTC, AleksandrinaKovachka approved these changes

2021-04-09 09:25 UTC, adikrasimirowa commented on html/userDetails.html
> +        <!-- <form class="wrapper upload">
@sharkoo0 това да го трия  ли или ще ти трябва за нещо друго :D

2021-04-09 10:04 UTC, yavorp commented on html/userDetails.html
> +        <!-- <form class="wrapper upload">
@adikrasimirowa, ползваме гит, за да не се налага да се прави това. В гит историята старата версия може да бъде намерена и да си я използваш в бъдеще

2021-04-10 21:43 UTC, merged