Feature/popup windows dani
sharkoo0/WebTEX pull request #25
Opened 2021-04-09 10:36 UTC by sharkoo0

2021-04-12 08:48 UTC, yavorp commented on html/userDetails.html
> +                </fieldset>
Махни `<br>`

2021-04-12 10:12 UTC, sharkoo0 commented on html/userDetails.html
> +                </fieldset>
Вече са премахните от всички файлове, ако не съм пропуснал някъде.

2021-04-12 13:15 UTC, adikrasimirowa approved these changes

2021-04-12 20:58 UTC, yavorp requested changes
Това, което е направено е добре, но има места, на които може да преизползвате дадени стилове, например за бутоните и тяхното font-family  пропърти

2021-04-12 20:58 UTC, yavorp commented on html/myFiles.html
> +            <a href="sharedFiles.html"><button class="upload-btn">Shared files</button></a>
Изберете си само `<a>` или бутон, така както е написано тук, семантично не е правилно. Имаше подобен коментар в минал PR

2021-04-12 20:58 UTC, yavorp commented on html/registration.html
> +            <span>Have an Account? <a href="login.html">Sign in now!</a></span>
`span` не е най-семантичният таг, тук може да използвате `<p>`, защото формата затваря блоков елемент в този случай inline свойството на span-a не ви е от полза

2021-04-12 20:58 UTC, yavorp commented on css/userDetails.css
> +    font-family: 'Montserrat', sans-serif;
Може би е по-полезно за всеки бутон да сложите съответния шрифт

2021-04-16 11:09 UTC, adikrasimirowa commented on css/userDetails.css
> +    font-family: 'Montserrat', sans-serif;
ще го оправим в следващ PR

2021-04-16 14:59 UTC, yavorp approved these changes
Променете това, което съм искал

2021-04-16 15:00 UTC, merged