Merge to master
sharkoo0/WebTEX pull request #27
Opened 2021-04-21 16:30 UTC by sharkoo0

Мислим, че всичко по frontend частта вече е готово.

2021-04-22 13:09 UTC, yavorp requested changes
Като цяло репото трябва да изчисти. Не ми харесва и използването на InnerHtml

2021-04-22 13:09 UTC, yavorp commented on css/auth.css
> +/* SIGN IN/UP SECTION */
Ненужен коментар

2021-04-22 13:09 UTC, yavorp commented on css/main.css
> +/* Style for myFiles,sharedFiles.html */
Ненужен коментар

2021-04-22 13:09 UTC, yavorp commented on css/main.css
> +/* Table content*/
Това нужно ли е да е тук?

2021-04-22 13:09 UTC, yavorp commented on html/userDetails.html
> +        <!-- NAVBAR -->
Отново ненужен коментар

2021-04-22 13:09 UTC, yavorp commented on html/userDetails.html
> +        <header>
Оправете форматирането

2021-04-22 13:09 UTC, yavorp commented on html/userDetails.html
> +        <script src="../js/uploadButton.js" defer></script>
Трябва да го преместите в хедъра

2021-04-22 13:09 UTC, yavorp commented on js/changePassword.js
> +    console.log("ashdfjka");
Този лог трябва ли да е тука?

2021-04-22 13:09 UTC, yavorp commented on js/changePassword.js
> +    console.log("ashdfjka");
Log?

2021-04-22 13:09 UTC, yavorp commented on js/myFiles.js
> +for (let i = 1; i <= 10; i++) {
Тази десетка откъде идва? Някакво магическо число, за да покажете демо на добавяне неща към таблицата ли е?

2021-04-22 13:09 UTC, yavorp commented on js/myFiles.js
> +//Not finished deleteFile()
Такива коментари не са окей. За такова напомнянене използвайте ишутата

2021-04-22 13:09 UTC, yavorp commented on js/uploadButton.js
> +    console.log("something")
Още един ненужен лог

2021-04-22 13:09 UTC, yavorp commented on js/myFiles.js
> +    td4.innerHTML = '<input class="picturre-download" type="Image" src="../images/download-solid.png" class="action-buttons">';
Този метод на добавяне на елементи не е много красив. Лично аз предпочитам да си добавяте елементите чрез DOM API-to. На упражнението показахме защо този метод за добавяне не е за предпочитане особено, когато имаме стойности, които са дошли от потребителите

2021-04-22 13:46 UTC, sharkoo0 commented on js/myFiles.js
> +for (let i = 1; i <= 10; i++) {
Да, това сме го сложили просто, за да се добавят някакви редове и да се види как изглежда таблицата на страницата.

2021-04-22 21:14 UTC, adikrasimirowa commented on js/myFiles.js
> +    td4.innerHTML = '<input class="picturre-download" type="Image" src="../images/download-solid.png" class="action-buttons">';
така става ли ?  -> https://github.com/sharkoo0/WebTEX/pull/29#issue-621543161

2021-04-25 08:55 UTC, sharkoo0 commented
> Като цяло репото трябва да изчисти. Не ми харесва и използването на InnerHtml

В PR-а, който Ади е направила е оправен проблемът с InnerHTML-a.

2021-04-26 18:18 UTC, yavorp approved these changes
Тези забележки няма за какво да ги оправяте за сега. Във финалната версия, ако имате време ги оправяйте

2021-04-26 18:18 UTC, yavorp commented on html/myFiles.html
> +            <div class="div-table">
този див не знам защо не го замените с article

2021-04-26 18:18 UTC, yavorp commented on html/registration.html
> +                <div class="input-container">
Това може да бъде section

2021-04-26 18:18 UTC, yavorp commented on html/sharedFiles.html
> +        <section class="upload-section">
Да имате една секция само не знам дали е особено добре

2021-04-27 11:06 UTC, merged